name: Build and Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build binaries
        run: |
          # Build for Windows amd64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ip-switcher-windows-amd64.exe -ldflags="-s -w" .
          
          # Build for Linux amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ip-switcher-linux-amd64 -ldflags="-s -w" .
          
          # Build for macOS arm64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ip-switcher-darwin-arm64 -ldflags="-s -w" .

      - name: List built files
        run: |
          ls -la ip-switcher-*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ip-switcher-windows-amd64.exe
            ip-switcher-linux-amd64
            ip-switcher-darwin-arm64
          draft: false
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}