name: Build Only

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build binaries
        run: |
          # Build for Windows amd64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ip-switcher-windows-amd64.exe -ldflags="-s -w" .
          
          # Build for Linux amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ip-switcher-linux-amd64 -ldflags="-s -w" .
          
          # Build for macOS arm64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ip-switcher-darwin-arm64 -ldflags="-s -w" .

      - name: List built files
        run: |
          ls -la ip-switcher-*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ip-switcher-binaries
          path: |
            ip-switcher-windows-amd64.exe
            ip-switcher-linux-amd64
            ip-switcher-darwin-arm64